services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      npm run migration:run && npm run build && npm run start:prod
      "

  db:
    image: postgres:15
    container_name: url-shortener-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
